# Spring Application Configurations
spring:
  application:
    name: api-gateway

# Server Configurations
server:
  port: 8075

# Zuul Properties Configuration
zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  host:
    connect-timeout-millis: 80000
    socket-timeout-millis: 80000

  #  Uncomment to disable auto-registering all services read from Eureka
  #  ignoredServices: '*'
  routes:
    prospect-service:
      path: /tweets/**
      serviceId: twitter-service-v1

      

# Eureka Client Configurations
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:9761/eureka/

# Security
security:
  user:
    name: admin
    password: admin
    
hystrix:
  command.default.execution.isolation:
    strategy: THREAD
    thread:
      timeoutInMilliseconds: 80000